title: Lecture

status:
  draft: true
  unlisted: true
  listed: true

tabs:
  content:
    columns:
      - width: 1/1

        fields:
          cover:
            extends: fields/cover
          intro:
            type: writer
          details:
            extends: fields/section
            label: Details
          before:
            extends: fields/cover
            width: 1/2
          after:
            extends: fields/cover
            width: 1/2
          quote:
            extends: fields/section
            label: Quote
  info:
    fields:

      client:
        width: 1/3
        label: Client
        type: text
      date:
        width: 1/3
        type: date
        label: Rok realizace
      place:
        width: 1/3
        type: text
        label: Lokalita
      industry:
        width: 1/2
        type: tags
        label: Obor podnikání
      solutions:
        type: multiselect
        label: Služby
        options:
          type: query
          query: site.index.filterBy("intendedTemplate", "in", ["solution"])
          text: "{{ page.title }}"
      space:
        width: 1/2
        type: tags
        label: Typ prostoru
      production:
        width: 1/2
        type: tags
        label: Výroba
      size:
        width: 1/3
        type: text
        label: Velikost
      hash:
        width: 2/3
        type: tags
        label: Hashtags
      team:
        width: 1/1
        type: multiselect
        options:
          type: query
          query: site.index.filterBy("intendedTemplate", "in", ["employee"])
          text: "{{ page.title }}"
          value: "{{ page.title }}"

      concept:
        width: 1/3
        label: Koncept
        type: text
      photo:
        width: 1/3
        type: text
      collabs:
        width: 1/3
        type: text

  gallery:
    columns:
      - width: 2/3
        fields:
          gallery:
            width: 1/1
            type: files
            template: cover
            info: "{{ file.dimensions }}"
            uploads:
              template: cover
            image:
              ratio: 5/4
              cover: true
            layout: cards
            size: large
            empty: No images yet
      - width: 1/3
        fields:
          

  testimonial:
    columns:
      - width: 2/3
        fields:
          testimonialQuote:
            type: writer
            label: Quote

      - width: 1/3
        fields:
          
          testimonialAuthor:
            type: text
            label: Author
          testimonialPosition:
            type: text
            label: Position
          testimonialImage:
            type: files
            label: Image/Logo
            template: logo
            info: "{{ file.dimensions }}"
            uploads:
              template: logo
            image:
              ratio: 4/5
              cover: true
            max: 1
            layout: cards
            size: small
  
  extras:
    columns:
      - width: 2/3
        fields:
          extras:
            extends: fields/section

      - width: 1/3
        fields:
          password:
            type: text

  meta: tabs/meta/page