title: Lecture

status:
  draft: true
  unlisted: true
  listed: true

tabs:
  content:
    columns:
      - width: 2/3

        fields:
          hero:
            extends: fields/hero
          details:
            type: writer
          quote:
            type: writer
          footnote:
            type: writer
          

      - width: 1/3
        fields:
          client:
            label: Client
            type: text
          concept:
            label: Koncept
            type: text
          date:
            type: date
            label: Rok realizace
          place:
            type: text
            label: Lokalita
          industry:
            type: tags
            label: Obor podnikání
          space:
            type: tags
            label: Typ prostoru
          hash:
            type: tags
            label: Hashtags

  gallery:
    columns:
      - width: 2/3
        fields:
          gallery:
            width: 1/1
            type: files
            template: image
            info: "{{ file.dimensions }}"
            uploads:
              template: image
            image:
              ratio: 5/4
              cover: true
            layout: cards
            size: large
            empty: No images yet
      - width: 1/3
        fields:
          author:
            type: text

  testimonial:
    columns:
      - width: 2/3
        fields:
          testimonialQuote:
            type: writer
            label: Quote

      - width: 1/3
        fields:
          
          testimonialAuthor:
            type: text
            label: Author
          testimonialPosition:
            type: text
            label: Position
          testimonialImage:
            type: files
            label: Image/Logo
            template: logo
            info: "{{ file.dimensions }}"
            uploads:
              template: logo
            image:
              ratio: 4/5
              cover: true
            min: 1
            layout: cards
            size: small
    

  meta: tabs/meta/page