title: Services

tabs:
  solutions:
    columns:
      - width: 2/3
        sections:
          listed:
            extends: sections/solutions
            headline: Solutions
            status: listed

      - width: 1/3
        sections:
          drafts:
            extends: sections/solutions
            headline: Drafts
            layout: list
            status: draft
          unlisted:
            extends: sections/solutions
            headline: Archive
            layout: list
            status: unlisted
      
  content:
    columns:
      - width: 3/4
        fields:
          hero:
            extends: fields/hero

          process:
            type: structure
            fields:
              step:
                type: number
              label:
                type: text
              figure:
                type: files
                template: image
                info: "{{ file.dimensions }}"
                max: 1
                uploads:
                  template: image
                image:
                  ratio: 5/4
                  cover: true
              detail:
                type: writer

      - width: 1/4
        sticky: true
        fields:
          order:
            type: structure 
            fields:
              label:
                label: Choose Section Layout
                type: select
                options: query
                query:
                  fetch: page.getCurrentAndGlobalSnippets
                  text: "{{ item.text }}"
                  value: "{{ item.value }}"

  meta: tabs/meta/page