name: 🔨 Staging Deployment

on:
  push:
    branches:
      - main
      - staging
    tags:
      - '*'

jobs:
  deploy:
    name: 🚀 Fast Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 185.102.21.205
          username: jiriklusak.cz
          password: ${{ secrets.FTP_PASSWORD || '3kNWXaeG' }}
          server-dir: public_html/projects/U1/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/scripts/**
            **/bs-config.js
            **/kirby/**
            **/media/**
            **/cache/**